rest:
  auth-open: true #jwt鉴权机制是否开启(true或者false)
  sign-open: true #签名机制是否开启(true或false)

jwt:
  header: Authorization   #http请求头所需要的字段
  secret: wy19960921        #jwt秘钥
  expiration: 2592000      #7天 单位:秒
  auth-path: auth         #认证请求的路径
  md5-key: takeaway      #md5加密混淆key

server:
  port: 8080

spring:
  profiles:
    active: dev-pc
  mvc:
    static-path-pattern: /res/**
    view:
      prefix: /view/
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/takeaway?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: wy1996
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    #连接超时时间
    timeout: 10000
#    aop:
#      proxy-target-class: true

mybatis-plus:
  global-config:
    id-type: 0
    #refresh-mapper: true
  mapper-locations: classpath*:/mybatis/**Mapper.xml
  typeAliasesPackage: net.novaborn.**.entity
  type-enums-package: net.novaborn.**.enums
log:
  path: admin-web-logs

logging:
  level:
    root: info
    net.novaborn: info

---
spring:
  profiles: dev-pc
  datasource:
    url: jdbc:mysql://192.168.0.17:3306/takeaway?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: wy1996
  redis:
    host: 192.168.0.17
    password: wy1996

#logging:
#    level:
#        root: info
#        net.novaborn: debug


---
spring:
  profiles: dev-mac
  datasource:
    url: jdbc:mysql://localhost:3306/takeaway?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: wy1996
  redis:
    host: localhost

#logging:
#  level:
#    root: info
#    net.novaborn: debug

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://cxy.novaborn.net:3306/takeaway?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Seoul
    username: takeaway
    password: takeaway123!
  redis:
    host: cxy.novaborn.net
  rabbitmq:
    host: cxy.novaborn.net
    username: xiaohun
    password: wy1996


---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/takeaway?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Seoul
    username: takeaway
    password: takeaway123!
  rabbitmq:
    username: xiaohun
    password: wy1996