FROM openjdk:11.0.6-slim

RUN echo "Asia/Seoul" > /etc/timezone && \
    dpkg-reconfigure --frontend noninteractive tzdata

VOLUME /tmp
ADD ./admin-web/target/admin-web-0.0.1-SNAPSHOT.jar /app.jar

ENV TZ=Asia/Seoul

ENV PARAMS=""

ENTRYPOINT ["sh","-c","java -jar /app.jar $PARAMS"]
