FROM rabbitmq:3.8.0-management-alpine

VOLUME /tmp

ENV TZ=Asia/Seoul

RUN wget -P /plugins https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.8.0/rabbitmq_delayed_message_exchange-3.8.0.ez

RUN rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange
