FROM openjdk:8u181-jdk-slim

RUN echo "Asia/Seoul" > /etc/timezone && \
    dpkg-reconfigure --frontend noninteractive tzdata

VOLUME /tmp
ADD ./wx-pay-web/target/wx-pay-web-0.0.1-SNAPSHOT.jar /app.jar

ENV TZ=Asia/Seoul

ENV PARAMS=""

ENTRYPOINT ["sh","-c","java -jar /app.jar $PARAMS"]
