FROM openjdk:11.0.3-jre-slim

RUN echo "Asia/Seoul" > /etc/timezone && \
    dpkg-reconfigure --frontend noninteractive tzdata

VOLUME /tmp
ADD ./user-web/target/user-web-0.0.1-SNAPSHOT.jar /app.jar

ENV TZ=Asia/Seoul

ENV PARAMS=""

ENTRYPOINT ["sh","-c","java -jar /app.jar $PARAMS"]
