FROM elasticsearch:7.9.1

VOLUME /tmp

ENV TZ=Asia/Seoul

RUN yum update -y && yum -y install wget unzip

RUN cd plugins && mkdir ik

RUN wget -P plugins/ik https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.7.1/elasticsearch-analysis-ik-7.7.1.zip

RUN cd plugins/ik && unzip elasticsearch-analysis-ik-7.7.1.zip
