FROM zhangguanzhang/docker.elastic.co.elasticsearch.elasticsearch:6.8.10

VOLUME /tmp

ENV TZ=Asia/Seoul

RUN apt-get update -y && apt-get -y install wget unzip

RUN cd plugins && mkdir ik

RUN wget -P plugins/ik https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.7.1/elasticsearch-analysis-ik-7.7.1.zip

RUN cd plugins/ik && unzip elasticsearch-analysis-ik-7.7.1.zip
