sys:
  printer-name: xp-58


server:
  port: 11996

spring:
  profiles:
    active: pro
  mvc:
    static-path-pattern: /res/**
    view:
      prefix: /view/
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/takeaway?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: wy1996
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    #连接超时时间
    timeout: 10000

mybatis-plus:
  global-config:
    id-type: 0
    #refresh-mapper: true
  mapper-locations: classpath*:/mybatis/**Mapper.xml
  typeAliasesPackage: net.novaborn.**.entity
  type-enums-package: net.novaborn.**.enums
log:
  path: wx-pay-web-logs

logging:
  level:
    root: info
    net.novaborn: info

---
spring:
  profiles: dev-pc
  datasource:
    url: jdbc:mysql://192.168.0.17:3306/takeaway?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: wy1996
  redis:
    host: 192.168.0.17
    password: wy1996
  rabbitmq:
    host: 192.168.0.17
    username: xiaohun
    password: wy1996

#logging:
#    level:
#        root: info
#        net.novaborn: debug


---
spring:
  profiles: dev-mac
  datasource:
    url: jdbc:mysql://localhost:3306/takeaway?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: wy1996
  redis:
    host: localhost

#logging:
#  level:
#    root: info
#    net.novaborn: debug

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://cxy.novaborn.net:3306/takeaway?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Seoul
    username: takeaway
    password: takeaway123!
  redis:
    host: cxy.novaborn.net
    password: wy1996
  rabbitmq:
    host: cxy.novaborn.net
    username: xiaohun
    password: wy1996


---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://cxy.novaborn.net:3306/takeaway?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Seoul
    username: takeaway
    password: takeaway123!
  redis:
    password: wy1996
  rabbitmq:
    username: xiaohun
    password: wy1996